package secureMulticast.event;

import java.util.*;

/**
 * <p> This interface allows implementing a class capable of listening to LKH events. These events
 * can be generated by a new SEK, a new joining, a new leaving, etc.
 *
 * @author  Oscar Burgos & Daniel Jarne
 * @version 1.1, 01/10/04
 */
public interface LKHListener extends EventListener
{
	/**
	 * Abstract method to implement a function to reply to a detected event.
	 */
	public abstract void LKHEventPerformed(LKHEvent e);
}